# Generated by Django 2.2.6 on 2020-06-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('ci', models.IntegerField(unique=True, verbose_name='Carnet de Identidad')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo electronico')),
                ('estado', models.IntegerField(choices=[(0, 'De Baja'), (1, 'Activo')], default=True, verbose_name='Estado')),
                ('prioridad', models.IntegerField(choices=[(0, 'Usuario'), (1, 'Administrador'), (2, 'Super Administrador')], default=0, verbose_name='Tipo de Usuario')),
                ('unidad', models.CharField(default='Semillas', max_length=200, verbose_name='Unidad')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
