# Generated by Django 2.2.6 on 2020-06-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='id_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partida.Partida'),
        ),
    ]
