# Generated by Django 2.2.6 on 2020-06-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_auto_20200604_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['nombre']},
        ),
    ]
