# Generated by Django 2.2.6 on 2020-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_retorno', models.DateTimeField()),
                ('tiempo', models.CharField(max_length=200)),
                ('motivo', models.CharField(max_length=900)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
