# Generated by Django 3.0.7 on 2020-06-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movilidad',
            options={'ordering': ['marca']},
        ),
    ]
