# Generated by Django 2.2.6 on 2020-06-13 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movilidad', '0001_initial'),
        ('programa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=999)),
                ('lugar', models.CharField(max_length=900)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('precio_unitario', models.FloatField()),
                ('precio_cantidad', models.FloatField()),
                ('precio_total', models.FloatField()),
                ('numero_memo', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_movilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movilidad.Movilidad')),
                ('id_programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.Programa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
