# Generated by Django 2.2.6 on 2020-08-26 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programa', '0001_initial'),
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('subprograma', models.CharField(max_length=900)),
                ('lugar', models.CharField(max_length=900)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('kilometraje', models.IntegerField(default=0)),
                ('combustible', models.IntegerField(default=0)),
                ('kilometraje_viaje', models.IntegerField(default=0)),
                ('numero_memo', models.IntegerField(default=0)),
                ('resolucion_administrativa', models.IntegerField(default=0)),
                ('observacion', models.CharField(default='sin observacion', max_length=999)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_movilidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movilidad.Movilidad')),
                ('id_programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.Programa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('unidad_liquidacion', models.CharField(max_length=50)),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Formulario')),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partida.Partida')),
            ],
        ),
    ]
