# Generated by Django 2.2.6 on 2020-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuente', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('glosa_uno', models.CharField(max_length=200)),
                ('glosa_dos', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
