# Generated by Django 3.0.7 on 2020-06-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuente', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('glosa_uno', models.CharField(max_length=200)),
                ('glosa_dos', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_programa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programa.Programa')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
